//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class single
    {
        public string GUID { get; set; }
        public Nullable<int> SingleIntNumber { get; set; }
        public Nullable<J.DB.Enum.single.SingleIntEnum> SingleIntEnum { get; set; }
        public Nullable<decimal> SingleMoney { get; set; }
        public Nullable<System.DateTime> SingleDatetime { get; set; }
        public string SingleVarchar { get; set; }
        public string SingleLongVarchar { get; set; }
        public Nullable<bool> SingleBit { get; set; }
    }
}
