//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class single
    {
        public string GUID { get; set; }
        public Nullable<int> SingleIntNumber { get; set; }
        public Nullable<int> SingleIntEnum { get; set; }
        public Nullable<decimal> SingleMoney { get; set; }
        public Nullable<System.DateTime> SingleDatetime { get; set; }
        public string SingleVarchar { get; set; }
        public string SingleLongVarchar { get; set; }
        public Nullable<bool> SingleBit { get; set; }
    }
}
