//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class single
    {
        public string GUID { get; set; }
        public int SingleIntNumber { get; set; }
        public J.DB.Enum.single.SingleIntEnum SingleIntEnum { get; set; }
        public decimal SingleMoney { get; set; }
        public System.DateTime SingleDatetime { get; set; }
        public string SingleVarchar { get; set; }
        public string SingleLongVarchar { get; set; }
        public bool SingleBit { get; set; }
    }
}
