//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadfile
    {
        public string GUID { get; set; }
        public string userID { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual user user { get; set; }
    }
}
