//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.user_loginlogs = new HashSet<user_loginlog>();
        }
    
        public string GUID { get; set; }
        public string ShowName { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual ICollection<user_loginlog> user_loginlogs { get; set; }
    }
}
